# Generated by Django 4.2.2 on 2023-06-19 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo_cover', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('notebook_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_mvp', models.BooleanField(default=False)),
            ],
        ),
    ]
