# Generated by Django 4.2.2 on 2023-06-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_notebook_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='photo_cover',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
