# Generated by Django 4.2.2 on 2023-06-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_alter_notebook_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='user_id',
            new_name='user',
        ),
    ]
