# Generated by Django 4.2.2 on 2023-06-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
