# Generated by Django 4.2.2 on 2023-07-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_rename_user_id_notebook_user'),
        ('notes', '0003_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.notebook'),
        ),
    ]
