# Generated by Django 4.2.2 on 2023-07-21 19:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='main_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
