# Generated by Django 4.2.2 on 2023-08-04 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_main_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
