# Generated by Django 4.2.2 on 2023-07-26 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sharednotes', '0002_alter_sharednote_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednote',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True),
        ),
    ]
